name: CI

on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
      - run: npm ci
      - run: npm exec eslint .
